steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gsutil', 'cp', '-r', 'gs://teste-jrtrend/.ssh', '/builder/home/']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: /bin/bash
  args: ['-c', 'chmod 400 /builder/home/.ssh/id_rsa']
- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  args:
    - "-c"
    - |
      ls -l /workspace/site/
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'beta', 'compute', 'scp', '--recurse', '/workspace/site/ ', '--zone=us-central1-a', 'build@pipeline:/tmp/', '--ssh-key-file=/builder/home/.ssh/id_rsa' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'beta', 'compute', 'ssh', '--zone=us-central1-a', 'build@pipeline', '--ssh-key-file=/builder/home/.ssh/id_rsa', '--', 'sudo cp -fvR /tmp/site/* /var/www/html' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'beta', 'compute', 'ssh', '--zone=us-central1-a', 'build@pipeline', '--ssh-key-file=/builder/home/.ssh/id_rsa', '--', 'sudo systemctl restart  httpd' ]
