steps:
- name: 'bash'
  args: ['echo', 'I am running a bash command']
- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  args:
    - "-c"
    - |
      getent passwd
      #chmod 777 /workspace/pub;
      #gcloud beta compute ssh  --ssh-key-file=/workspace/pub  --zone "us-central1-a" --strict-host-key-checking=no  "pipeline" --project "jrtrend-206104" --command 'mkdir -pv /tmp/teste6/ && ls -ld /tmp/teste6' 
