steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: /bin/bash
  args: ['-c', 'chmod 400 /builder/home/.ssh/build']
- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  args:
    - "-c"
    - |
      chmod 0600 /workspace/pub; ls -ld ~/.ssh
      gcloud beta compute ssh  --ssh-key-file=/workspace/pub  --strict-host-key-checking=no --zone "us-central1-a"   "pipeline" --project "jrtrend-206104" --command 'mkdir -pv /tmp/teste6/ && ls -ld /tmp/teste6' 
