steps:
- name: 'bash'
  args: ['echo', 'I am running a bash command']
- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  args:
    - "-c"
    - |
      gcloud beta compute ssh --zone "us-central1-a" "pipeline" --project "jrtrend-206104" --command 'mkdir -pv /tmp/teste6/ && ls -ld /tmp/teste6'
