steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  args:
    - "-c"
    - |
       gcloud beta compute ssh  --strict-host-key-checking=no --force-key-file-overwrite --zone us-central1-a juniiin16@pipeline --command 'mkdir -pv /tmp/teste4/ && ls -ld /tmp/teste3'
