steps:
- name: gcr.io/cloud-builders/gcloud
  volumes:
  - name: 'ssh'
    path: '/builder/home/.ssh/'
  entrypoint: "bash"
  args:
    - "-c"
    - |
      cat /builder/home/.ssh/google_compute_engine.pub
