steps:
- name: 'bash'
  args: ['echo', 'I am running a bash command']
- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  args:
    - "-c"
    - |
      echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4EjwMsHrLXwrHWtfPVBycg4ZB2vPDs048LqQ7YYxwu9OoQ6JkPnVcxlXTDmQqpprarsP9icBwNODP6S/x6ridgEAsyj/nhXw6oYLsmNqrmpLpnlse3xuU5R5h6cWSQBEGIsImnxtQhLiHvq5xIzRBBgwuLbzLeo1GkEko5LRZVmdnaenKo4ptkLCl8HaAK9CCaKJ/Eq5e7QsH/g3Bl+yUHqcXf4kIHsni/5LRj7+qozySMpbkTcZy0TLLpLYWf92+8CnGuMZ44qKa+ct7RB+t40nuPimQWHuY8IZ+eJf4qGuQ7gAwfHwB1dX5oIWaT6hftJ2SugI5YqIiUVO0BfRRcXu1jC8erl1ReFErFHcOCEnbGmtqfsbzheyDRRkfpsuB659qa+mU5fW3d/tDjfo0eGT0xtT01wgfEl924ClmxU0p8yy5jBcJhq6D3Hrkvt45sywwviWuWkoOEPNmHI5B+KYlWrhjnoAKKE5Aeme3Ev1SYfYULx7B0qWbUGD5iJs= francisco.junio@fscojrnote" >  /workspace/google_compute_engine.pub; ls -ltr  /workspace/; gcloud beta compute ssh --ssh-key-file=/workspace/google_compute_engine.pub  --zone "us-central1-a" --strict-host-key-checking=no  "pipeline" --project "jrtrend-206104" --command 'mkdir -pv /tmp/teste6/ && ls -ld /tmp/teste6' 
